# For physics topics, use the specific subtopics, e.g. "Astrophysics"
topic: "Computer Science"
# An empty list here will include all categories in a topic
# Use the natural language names of the topics, found here: https://arxiv.org
# Including more categories will result in more calls to the large language model
categories: ["Artificial Intelligence", "Computation and Language"]

# Relevance score threshold. abstracts that receive a score less than this from the large language model
# will have their papers filtered out.
#
# Must be within 1-10
threshold: 7

# A natural language statement that the large language model will use to judge which papers are relevant 
#
# For example:
"I am interested in large language models, particularly new algorithms, security vulnerabilities and issues of bias or offensive content,"
"I am also interesdted in text summarization, applications of large lengauge models to the legal profession and chatting with documents."
#  
#
# This can be empty, which just return a full list of papers with no judgement or filtering,
# in whatever order arXiv responds with.
interest: |
  1. Large language model pretraining and finetunings
  2. Text summarization, chatting with documents
  3.  Security vulberabilities
  4.  Copyright issues
  5.  Offensive content, RLHF, bias
  6. Not interested in paper focus on specific languages, e.g., Arabic, Chinese, etc.
